services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: psql-container
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker123
      POSTGRES_DB: python-gym-control
    ports:
      - "5433:5432"
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

volumes:
  db-postgres-data:

networks:
  dev-network:
    driver: bridge