CREATE SCHEMA webuser AUTHORIZATION python-gym-control;

DROP TABLE IF EXISTS WEBUSER.TB_SCHEDULE;
DROP TABLE IF EXISTS WEBUSER.TB_ACTIVITY;
DROP TABLE IF EXISTS WEBUSER.TB_MEMBER;
DROP TABLE IF EXISTS WEBUSER.TB_PLAN;
DROP TABLE IF EXISTS WEBUSER.TB_INSTRUCTOR;

CREATE TABLE WEBUSER.TB_INSTRUCTOR (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_birth DATE NOT NULL,
    address TEXT,
    phone VARCHAR(20),
);

CREATE TABLE WEBUSER.TB_PLAN (
    id SERIAL PRIMARY KEY,
    plan VARCHAR(100) NOT NULL,
);

CREATE TABLE WEBUSER.TB_MEMBER (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_birth DATE NOT NULL,
    address TEXT,
    phone VARCHAR(20),
    email VARCHAR(100) NOT NULL,
    type_plan INTEGER REFERENCES WEBUSER.TB_PLAN(id),
    start_date DATE NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_ACTIVITY (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    instructor INTEGER REFERENCES WEBUSER.TB_INSTRUCTOR(id) ON DELETE CASCADE,
    date TIMESTAMP NOT NULL,
    duration INT NOT NULL,
    capacity INT NOT NULL,
    type_plan INT REFERENCES WEBUSER.TB_PLAN(id),
    active BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_SCHEDULE (
    id SERIAL PRIMARY KEY,
    activity INTEGER REFERENCES WEBUSER.TB_ACTIVITY(id) ON DELETE CASCADE,
    member INTEGER REFERENCES WEBUSER.TB_MEMBER(id) ON DELETE CASCADE
);